openapi: '3.0.2'
info:
  title: Project YangBlog
  description: A blog project of Yang Bofan
  version: '1.0'
servers:
  - url: https://localhost:8080
paths:
  /Signin:
    get:
      tags:
        - UserStatus
      description: '返回用户登陆界面'
      operationId: getSigninView
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/SigninHtml"
    post:
      tags:
        - UserStatus
      description: '接收用户登陆信息'
      operationId: signin
      requestBody:
        required: true
        content:
          text/json:
            schema:
              type: "object"
              properties:
                username:
                  type: "string"
                password:
                  type: "string"
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/Signin"

  /Register:
    get:
      tags:
        - UserStatus
      description: '返回用户注册界面'
      operationId: getRegisterView
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/RegisterHtml"
    post:
      tags:
        - UserStatus
      description: '接收用户注册信息'
      operationId: Register
      requestBody:
        required: true
        content:
          text/json:
            schema:
              type: "object"
              properties:
                username:
                  type: "string"
                email:
                  type: "string"
                phoneNumber:
                  type: "string"
                password:
                  type: "string"
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/Register"

  /BlogMain:
    get:
      tags:
        - BlogContents
      description: '返回博客文章界面'
      operationId: getBlogMainView
      responses:
        '200':
          description: OK
          content:
            text/html:
              schema:
                $ref: "#/components/schemas/BlogMainHtml"

    post:
      tags:
        - BlogContents
      description: '接收用户对博客的评论'
      operationId: comments
      requestBody:
        required: true
        content:
          text/json:
            schema:
              type: "object"
              properties:
                comments:
                  type: "string"
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/BlogMain"

  /Post:
    get:
      tags:
        - BlogContents
      description: '创建新博客文章界面'
      operationId: getPostView
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/PostHtml"
    post:
      tags:
        - BlogContents
      description: '接收用户编辑的博客内容'
      operationId: post
      requestBody:
        required: true
        content:
          text/json:
            schema:
              type: "object"
              properties:
                Username:
                  type: "string"
                Date:
                  type: "string"
                Title:
                  type: "string"
                Tag:
                  type: "string"
                Body:
                  type: "string"
                view:
                  type: "string"
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/Post"


components:
  schemas:

    SigninHtml:
      type: "string"
    Signin:
      type: "object"
      properties:
        email:
          type: "string"
        view:
          type: "string"

    RegisterHtml:
      type: "string"      
    Register:
      type: "object"
      properties:
        username:
          type: "string"
        email:
          type: "string"
        phoneNumber:
          type: "string"
        view:
          type: "string"

    BlogMainHtml:
      type: "string"
      properties:
        username:
          type: "string"
        date:
          type: "string"
        title:
          type: "string"
        tag:
          type: "string"
        body:
          type: "string"
    BlogMain:
      type: "object"
      properties:
        comments:
          type: "string"
        view:
          type: "string"

    PostHtml:
      type: "string"
    Post:
      type: "object"
      properties:
        Username:
          type: "string"
        Date:
          type: "string"
        Title:
          type: "string"
        Tag:
          type: "string"
        Body:
          type: "string"
        view:
          type: "string"