openapi: '3.0.2'
info:
  title: Project YangBlog
  description: A blog project of Yang Bofan
  version: '1.0'
servers:
  - url: https://localhost:8080
paths:

  /Signin:

    get:
      summary: '显示登陆界面'
      tags:
        - Class UserStatus
      description: '使用view返回html登陆界面'
      operationId: getSigninView
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/SigninHtml"
        
    post:
      summary: '接收登陆信息'
      tags:
        - Class UserStatus
      description: '接收用户登陆信息'
      operationId: Signin
      requestBody:
        required: true
        content:
          text/json:
            schema:
              $ref: "#/components/schemas/Signin"
      responses:
        '200':
          description: 数据匹配，登录成功
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/SigninHtml"
        '201':
          description: 账户信息与数据库不符，登陆失败
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/ErrorMessage"

  /Register:
    get:
      tags:
        - Class UserStatus
      description: '使用view返回html注册界面'
      summary: '显示新用户注册界面'
      operationId: getRegisterView
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/RegisterHtml"
    post:
      tags:
        - Class UserStatus
      description: '接收用户注册信息'
      summary: '接收用户注册信息'
      operationId: Register
      requestBody:
        required: true
        content:
          text/html:
            schema:
             $ref: "#/components/schemas/RegisterHtml"
              
      responses:
        '200':
          description: OK
          content:
            text/json:    
              schema:
                $ref: "#/components/schemas/UserInformation"

  /BlogMain:
    get:
      tags:
        - Class BlogContents
      description: '使用view返回html文章界面'
      summary: '返回博客文章界面'
      operationId: getBlogMainView
      requestBody:
        required: true
        content:
          text/json:
            schema:
              $ref: "#/components/schemas/BlogBody"
              comments:
                  type: "string"
      responses:
        '200':
          description: OK
          content:
            text/html:
              schema:
                $ref: "#/components/schemas/BlogMainHtml"
            
    post:
      tags:
        - Class BlogContents
      description: '用于接收用户对博客的评论内容'
      summary: '接收博客评论'
      operationId: comments
      requestBody:
        required: false
        content:
          text/json:
            schema:
              $ref: "#/components/schemas/Comments"
              
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/PostHtml"

  /Post:
    get:
      tags:
        - Class BlogContents
      description: '创建新博客文章界面'
      operationId: getPostView
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/PostHtml"
    post:
      tags:
        - Class BlogContents
      description: '接收用户编辑的博客内容'
      operationId: post
      requestBody:
        required: true
        content:
          text/html:    
              schema:
                $ref: "#/components/schemas/PostHtml"
      responses:
        '200':
          description: OK
          content:
            text/json:    
              schema:
                $ref: "#/components/schemas/BlogBody"


components:
  schemas:
    
    UserInformation:
      type: object
      required:
        - "username"
        - "email"
        - "phoneNumber"
        - "password"
      properties:
        username:
          type: "string"
        email:
          type: "string"
        phoneNumber:
          type: "integer"
        password:
          type: "string"
        view:
          type: "string"

    BlogBody:
      type: object
      required:
        - "username"
        - "date"
        - "title"
        - "body"
      properties:
        username:
          type: "string"
        date:
          type: "string"
        title:
          type: "string"
        tag:
          type: "string"
        body:
          type: "string"
        view:
          type: "string"

    Signin:
      type: "object"
      required:
        - "email"
        - "password"
      properties:
        email:
          type: "string"
        password:
          type: "string"
        view:
          type: "string"
    
    SigninHtml:
      type: "string"

    RegisterHtml:
      type: "string"   

    PostHtml:
      type: "string"     

    BlogMainHtml:
      type: "string"
    
    Comments:
      type: "object"
      properties:
        comments:
          type: "string"
        view:
          type: "string"

    ErrorMessage:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string